#!/usr/bin/env bash
# vim: set ts=3 sw=3 noet ft=sh :
#
# gen-toolchain.sh <profile> [--sysroot-bin <dir>]      (or: --all)
#
# Generate the wrapper toolchain a profile builds with:
#
#    toolchain-<TOOLCHAIN_NAME>/bin/<TOOLCHAIN_NAME>-gcc
#    toolchain-<TOOLCHAIN_NAME>/bin/<TOOLCHAIN_NAME>-g++
#
# The wrappers used to be hand-written files with the Buildroot sysroot path
# baked in as a literal, which is precisely what stopped a fresh checkout from
# building anything.  They are now derived from the profile.
#
# WHY A WRAPPER AT ALL, rather than passing flags through the recipe:
#
#   * ISA/ABI flags must be PREPENDED to every single invocation.  No libretro
#     core Makefile sets them, and a core that compiles one file without them
#     produces an object for the wrong ISA that links fine and faults on target.
#   * Optimisation flags must be APPENDED.  Many cores tack on their own "-O2"
#     after their platform block; for GCC the last -O wins, so a prepended -O3
#     is silently discarded.
#
# A single-token CC is deliberate: some cores do `ifeq ($(CC),gcc)`, which a
# multi-word "gcc -mcpu=..." would break.
#
# CORES CANNOT BE BUILT UNTIL THE CROSS TOOLCHAIN EXISTS.  This script refuses
# to emit a wrapper pointing at a compiler that is not there -- a wrapper that
# exec's a missing binary fails per-core, deep inside a build log, as a
# "command not found" that looks like a core problem rather than a missing
# Buildroot toolchain.

set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

die() { echo "gen-toolchain: $*" >&2; exit 1; }

kv_get() {
	awk -v key="$2" '
		/^[[:space:]]*(#|$)/ { next }
		$1 == key { $1 = ""; sub(/^[[:space:]]+/, ""); v = $0 }
		END { if (v != "") print v }
	' "$1"
}

gen_one() {
	local profile_name="$1" sysroot_override="$2"
	local prof="$BASE_DIR/profiles/${profile_name}.profile"
	[ -f "$prof" ] || die "no such profile: $prof"

	local name prefix isa opt compat sysroot_bin desc
	name="$(kv_get "$prof" TOOLCHAIN_NAME)"
	prefix="$(kv_get "$prof" CROSS_PREFIX)"
	isa="$(kv_get "$prof" ISA_FLAGS)"
	opt="$(kv_get "$prof" OPT_FLAGS)"
	conly="$(kv_get "$prof" C_ONLY_FLAGS)"
	compat="$(kv_get "$prof" COMPAT_HEADER)"
	sysroot_bin="${sysroot_override:-$(kv_get "$prof" SYSROOT_BIN)}"

	[ -n "$name" ]        || die "$profile_name: TOOLCHAIN_NAME not set"
	[ -n "$prefix" ]      || die "$profile_name: CROSS_PREFIX not set"
	[ -n "$isa" ]         || die "$profile_name: ISA_FLAGS not set"
	[ -n "$sysroot_bin" ] || die "$profile_name: no SYSROOT_BIN and no --sysroot-bin"

	# The precondition.  Build the toolchain first (for knulli: that board's
	# Buildroot toolchain), then the cores.
	local cc="${sysroot_bin}/${prefix}gcc" cxx="${sysroot_bin}/${prefix}g++"
	[ -x "$cc" ]  || die "$profile_name: no cross compiler at $cc -- build the toolchain before the cores"
	[ -x "$cxx" ] || die "$profile_name: no cross c++ at $cxx -- build the toolchain before the cores"

	local tcdir="$BASE_DIR/toolchain-${name}"
	mkdir -p "$tcdir/bin"

	# The compat header lives beside the wrappers and is referenced through
	# $(dirname $0), so the toolchain directory stays relocatable.
	local include=""
	if [ -n "$compat" ]; then
		[ -f "$tcdir/$compat" ] || die "$profile_name: COMPAT_HEADER $compat missing from $tcdir"
		include=' -include "$HERE/../'"${compat}"'"'
	fi

	local tool tool_opt
	for tool in gcc g++; do
		# C_ONLY_FLAGS go to the gcc wrapper only: they are C-language
		# diagnostics and g++ answers each one with "valid for C/ObjC but not
		# for C++" on every single compile.
		tool_opt="$opt"
		[ "$tool" = gcc ] && tool_opt="$opt${conly:+ $conly}"
		cat > "$tcdir/bin/${name}-${tool}" <<EOF
#!/bin/sh
# GENERATED by gen-toolchain.sh from profiles/${profile_name}.profile.
# Do not edit -- regenerate instead.
#
# ISA/ABI flags are PREPENDED: nothing in a core Makefile sets them and they
# must be on every invocation.  Optimisation flags are APPENDED: many cores add
# their own -O2 after their platform block and for GCC the last -O wins.
#
# NO_FAST_MATH=1 drops -ffast-math for one core.  make re-exports command-line
# variables to recipe subprocesses, so a per-core recipe arg reaches us here.
# Needed by cores that refuse to build under unsafe math (mednafen's
# OwlResampler.cpp and the vendored sqlite in play both #error on it).
TC=${sysroot_bin}
HERE=\$(dirname "\$0")
ISA="${isa}"
OPT="${tool_opt}"
[ -z "\$NO_FAST_MATH" ] && OPT="\$OPT -ffast-math"
exec "\$TC/${prefix}${tool}" \$ISA${include} "\$@" \$OPT
EOF
		chmod +x "$tcdir/bin/${name}-${tool}"
	done

	echo "gen-toolchain: $profile_name -> toolchain-${name}/bin/${name}-{gcc,g++} (via ${sysroot_bin})"
}

[ $# -gt 0 ] || die "usage: $0 <profile> [--sysroot-bin <dir>]   |   $0 --all"

PROFILES=()
SYSROOT=""
while [ $# -gt 0 ]; do
	case "$1" in
		--all)
			for _p in "$BASE_DIR"/profiles/*.profile; do
				_p="${_p##*/}"; PROFILES+=("${_p%.profile}")
			done
			;;
		--sysroot-bin) SYSROOT="$2"; shift ;;
		*)             PROFILES+=("$1") ;;
	esac
	shift
done

[ "${#PROFILES[@]}" -gt 0 ] || die "no profile given"
for p in "${PROFILES[@]}"; do gen_one "$p" "$SYSROOT"; done
