#!/bin/sh

case "$1" in
    suspend)
        knulli-brightness dispoff
        knulli-audio setSystemVolume mute
        ;;
    resume|thaw)
        knulli-brightness dispon
        knulli-audio setSystemVolume unmute
        ;;
esac

exit 0
