#!/bin/sh

# We only want to run the script if the board has lid capability
if ! knulli-board-capability "pwrled"; then
    exit 1
fi

case "$1" in
    thaw|resume)
        LED="$(/usr/bin/knulli-settings-get system.power.led)"
        if [ "$LED" = "0" ]; then
            knulli-power-led power off &
        else
            knulli-power-led power on &
        fi
        ;;
esac

exit 0
