#!/bin/bash

# workaround for wifi not working after standby / sleep

wifi_toggle() {
    knulli-wifi disable
    knulli-wifi enable
}

case "$1" in
    resume|thaw)
        wifi_toggle
        ;;
esac

exit 0
