#!/bin/sh

GTMP="/tmp"
DHOME="/userdata/system"
V_ARCH=$(uname -m)

# to be callable by any external tool
if test $# -eq 1
then
    REPORTNAME=$(basename "$1" | sed -e s+'^\([^.]*\)\..*$'+'\1'+)
    OUTPUTFILE=$1
else
    REPORTNAME="knulli-support-"$(date +%Y%m%d%H%M%S)
    OUTPUTFILE="/userdata/saves/${REPORTNAME}.tar.gz"
fi

TMPDIR="${GTMP}/${REPORTNAME}"

f_cp() {
    test -e "$1" && cp "$1" "$2"
}

d_cp() {
    test -d "$1" && cp -pr "$1" "$2"
}

if mkdir "${TMPDIR}" && mkdir "${TMPDIR}/system" "${TMPDIR}/joysticks" "${TMPDIR}/lirc" "${TMPDIR}/kodi" "${TMPDIR}/coredumps"
then
    if ! cd "${TMPDIR}"
    then
	echo "Change directory failed" >&2
	exit 1
    fi
else
    echo "Reporting directory creation failed" >&2
    exit 1
fi

# SYSTEM
DSYSTEM="${TMPDIR}/system"

# in case xorg is in use
if test -z "${DISPLAY}"; then
    export DISPLAY=$(getLocalXDisplay)
fi

dmesg 	         	> "${DSYSTEM}/dmesg.txt"
lsmod 	         	> "${DSYSTEM}/lsmod.txt"
ps -ef 	         	> "${DSYSTEM}/ps.txt"
df -h 	         	> "${DSYSTEM}/df.txt"
netstat -tuan    	> "${DSYSTEM}/netstat.txt"
lsusb -v         	> "${DSYSTEM}/lsusb.txt" 2>/dev/null
command -v tvservice >/dev/null && tvservice -m CEA 	> "${DSYSTEM}/tvservice-CEA.txt"
command -v tvservice >/dev/null && tvservice -m DMT 	> "${DSYSTEM}/tvservice-DMT.txt"
ifconfig -a             > "${DSYSTEM}/ifconfig.txt"
ip a                    > "${DSYSTEM}/ip-addr.txt"
ip r                    > "${DSYSTEM}/ip-route.txt"
# wifi link state: connmanctl says whether it associated, these say how well
iw dev                  > "${DSYSTEM}/iw-dev.txt" 2>/dev/null
iw phy phy0 info        > "${DSYSTEM}/iw-phy0-info.txt" 2>/dev/null
lspci                   > "${DSYSTEM}/lspci.txt"
lspci -v                > "${DSYSTEM}/lspci_v.txt"
hciconfig -a            > "${DSYSTEM}/bt-capabilities.txt"
amixer                  > "${DSYSTEM}/amixer.txt"
aplay -l                > "${DSYSTEM}/aplay-l.txt"
alsactl info            > "${DSYSTEM}/alsactl-info.txt"
knulli-audio list     > "${DSYSTEM}/knulli-audio-list.txt"
command -v glxinfo >/dev/null && glxinfo    > "${DSYSTEM}/glxinfo.txt"
command -v xrandr  >/dev/null && xrandr     > "${DSYSTEM}/xrandr.txt"
blkid                   > "${DSYSTEM}/disks.txt"
wpctl status            > "${DSYSTEM}/wireplumber.txt"
connmanctl technologies > "${DSYSTEM}/connman-technologies.txt"
connmanctl services     > "${DSYSTEM}/connman-services.txt"
knulli-systems        > "${DSYSTEM}/bios.txt"
knulli-version        > "${DSYSTEM}/knulli.version"
knulli-info           > "${DSYSTEM}/knulli.info"
ldconfig -p             > "${DSYSTEM}/ldcache.txt"
mount                   > "${DSYSTEM}/mount.txt"
env                     > "${DSYSTEM}/environment.txt"
top -b -n 1             > "${DSYSTEM}/top.txt"
knulli-services list    > "${DSYSTEM}/services.txt"
# get xrandr provider if x86 system only
if [ "${V_ARCH}" = "x86" -o "${V_ARCH}" = "x86_64" ]; then
    xrandr --listproviders  > "${DSYSTEM}/xrandr-providers.txt"
fi
f_cp /boot/boot/knulli.board                                 "${DSYSTEM}"
f_cp /boot/config.txt                                          "${DSYSTEM}"
f_cp /userdata/system/knulli.conf                            "${DSYSTEM}"
d_cp /userdata/system/logs                                     "${DSYSTEM}"
f_cp /var/log/messages                                         "${DSYSTEM}"
f_cp /userdata/system/configs/emulationstation/es_settings.cfg "${DSYSTEM}"
f_cp /userdata/system/configs/emulationstation/es_log.txt      "${DSYSTEM}"
f_cp /userdata/system/configs/emulationstation/es_input.cfg    "${DSYSTEM}"
f_cp /boot/knulli-boot.conf                                  "${DSYSTEM}"
f_cp /var/log/Xorg.0.log                                       "${DSYSTEM}"
f_cp /var/log/bluetooth-agent.log                              "${DSYSTEM}"
# resize.log
if [ -f /tmp/resize.log ]; then
    f_cp /tmp/resize.log                                       "${DSYSTEM}"
fi
# boot.log
if [ -f /var/run/boot.log ]; then
    f_cp /var/run/boot.log                                     "${DSYSTEM}"
fi

# clear passwords
# filter some dangerous options (may include some path with /userdata)
sed -i -e s+"^.*password.*$"+""+gI "${DSYSTEM}/logs/"*.log
sed -i -e s+"^.*user.*$"+""+gI "${DSYSTEM}/es_settings.cfg"
sed -i -e s+"^.*pass.*$"+""+gI "${DSYSTEM}/es_settings.cfg"
sed -i -e s+"^.*wifi.*$"+""+gI "${DSYSTEM}/knulli.conf"
sed -i -e s+"^.*retroachievements.*$"+""+gI "${DSYSTEM}/knulli.conf"
sed -i -e s+"^.*password.*$"+""+gI "${DSYSTEM}/knulli.conf"
sed -i -e s+"^.*token.*$"+""+gI "${DSYSTEM}/knulli.conf"
sed -i -e s+"^.*wifi.*$"+""+gI "${DSYSTEM}/knulli-boot.conf"

# Emulators configs
#d_cp /userdata/system/configs                           "${TMPDIR}/configs", disabled, too big

# joysticks
DJOYS="${TMPDIR}/joysticks"
find /dev/input > "${DJOYS}/inputs.txt"
for J in /dev/input/event*
do
    N=$(basename ${J})
    evtest --info "${J}"          > "${DJOYS}/evtest.${N}.txt"
    udevadm info -q all -n "${J}" > "${DJOYS}/udevadm.${N}.txt"
done
sdl2-jstest -l > "${DJOYS}/sdl2-jstest.txt"
cp "/var/run/sinden/p"*"/sinden-"*".log" "${DJOYS}" 2>/dev/null

# lirc
DLIRC="${TMPDIR}/lirc"
f_cp "${DHOME}/.config/lirc/lircd.conf" "${DLIRC}"

# kodi
DKODI="${TMPDIR}/kodi"
f_cp "${DHOME}/.kodi/userdata/Lircmap.xml"          	      "${DKODI}"
d_cp "${DHOME}/.kodi/userdata/addon_data/peripheral.joystick" "${DKODI}"
d_cp "${DHOME}/.kodi/userdata/remotes"              	      "${DKODI}"
f_cp "${DHOME}/.kodi/temp/kodi.log"                 	      "${DKODI}"

# core dumps
DCORE="${TMPDIR}/coredumps"
for C in /userdata/system/logs/core.*
do
    f_cp "${C}" "${DCORE}"
done

if ! (cd "${GTMP}" && tar cf -  "${REPORTNAME}" | gzip -c > "${OUTPUTFILE}")
then
    echo "Reporting zip creation failed" >&2
    exit 1
fi

rm -rf "${TMPDIR}"
echo "${OUTPUTFILE}"
exit 0
