#!/bin/sh

# Temp init to migrate files from old legacy repo to new one
# batocera.conf -> knulli.conf for example
# eventually will not be needed

BATOCERA_CONF="/userdata/system/batocera.conf"
KNULLI_CONF="/userdata/system/knulli.conf"

case "$1" in
start)
    if [ ! -f "$KNULLI_CONF" ] && [ -f "$BATOCERA_CONF" ]; then
        cp "$BATOCERA_CONF" "$KNULLI_CONF"
        mv "$BATOCERA_CONF" "${BATOCERA_CONF}.old"
    fi
    ;;
esac

exit 0
