#!/bin/sh

BIN="/usr/bin/trimui_inputd"

[ -f "$BIN" ] || exit 0

case "$1" in
    start)
        "$BIN" &
        ;;
    stop)
        killall -9 trimui_inputd 2>/dev/null || true
        ;;
esac

exit 0
