#!/bin/bash

BATTSAVER_DIR="/var/run/battery-saver/"
mkdir -p "$BATTSAVER_DIR"

GOVERNOR_SAVED="/var/run/battery-saver/governor.saved"
GOVERNOR=""

MODE="$(/usr/bin/knulli-settings-get system.batterysaver.mode)"

AGGRESSIVE="$(/usr/bin/knulli-settings-get system.batterysaver.aggressive)"

MUTE="$(/usr/bin/knulli-settings-get system.batterysaver.mute)"

check_pause() {
  # return 0 if any *.pause exists, else 1
  compgen -G "$BATTSAVER_DIR"/*.pause > /dev/null && return 0
  return 1
}

do_aggressive() {
  knulli-aggressive-saver on
}

do_idle() {
    case "$MODE" in
        dim)
            knulli-brightness dim
            [[ "$MUTE" == "1" ]] && knulli-audio setSystemVolume mute

            [[ "$AGGRESSIVE" == "1" ]] && do_aggressive
        ;;
        dispoff)
            [[ "$MUTE" == "1" ]] && knulli-audio setSystemVolume mute
            knulli-brightness dispoff

            [[ "$AGGRESSIVE" == "1" ]] && do_aggressive
        ;;
        suspend)
            knulli-suspend

        ;;
        shutdown)
            knulli-shutdown -s
        ;;
    esac
}

case "$1" in
    idle)
        if ! check_pause; then
            do_idle
        fi
    ;;
esac

exit 0
