#!/bin/bash
#
# Emit a Buildroot-style config fragment naming the libretro cores this drop
# actually contains.
#
# knulli-es-system reads it alongside .config, which is what makes es_systems.yml
# keep working now that the individual libretro-* packages are gone: the yml
# gates cores on BR2_PACKAGE_LIBRETRO_* symbols, and nothing sets those any more.
# It also drives the roms/ folder list -- knulli-es-system only creates
# datainit/roms/<system> for systems that have at least one usable core, so
# without this fragment the folders go missing too.
#
# Usage: gen-es-config.sh DROP_DIR CORES_SYMBOLS OUTPUT OUTPUT_LIST [EXCLUDE]
#
# DROP_DIR       drop/<profile> -- its cores/ dir is the ground truth
# CORES_SYMBOLS  core .so -> symbol table (cores.symbols)
# OUTPUT         config fragment to write
# OUTPUT_LIST    plain list of installed core .so names, written alongside it.
#                A symbol is coarser than a core: one package can install
#                several .so files (vice_x64, vice_xscpu64, ...) and a drop may
#                carry only some of them.  knulli-es-system uses this list to
#                drop the cores that are not really there, so es_systems.cfg
#                never offers a core RetroArch would fail to load.
# EXCLUDE        core names (no _libretro.so) this device must not offer.  The
#                drop is keyed on the ABI profile, so a board that should not
#                run a core still receives it; those are dropped here, and
#                libretro-super.mk prunes the same list out of the squashfs.

DROP_DIR=$1
CORES_SYMBOLS=$2
OUTPUT=$3
OUTPUT_LIST=$4
EXCLUDE=$5

excluded() {
    for x in ${EXCLUDE}; do
        [ "$1" = "$x" ] && return 0
    done
    return 1
}

set -e

test -d "${DROP_DIR}/cores" || {
    echo "gen-es-config: no cores in ${DROP_DIR} -- was the drop built?" >&2
    exit 1
}
test -f "${CORES_SYMBOLS}" || {
    echo "gen-es-config: missing table ${CORES_SYMBOLS}" >&2
    exit 1
}

mkdir -p "$(dirname "${OUTPUT}")"

# Symbols for the cores present.  Sorted and deduplicated because several .so
# files can come from one package (boom3 / boom3_xp), and a duplicated line
# would be silently accepted but reads as a bug.
{
    echo "# Generated by gen-es-config.sh -- do not edit."
    echo "# libretro cores present in $(basename "${DROP_DIR}")."
    grep -vE '^[[:space:]]*(#|$)' "${CORES_SYMBOLS}" | while read -r so symbol; do
        [ -n "$symbol" ] || continue
        excluded "${so%_libretro.so}" && continue
        [ -e "${DROP_DIR}/cores/${so}" ] && echo "${symbol}=y"
    done | sort -u
} > "${OUTPUT}"

if [ -n "${OUTPUT_LIST}" ]; then
    mkdir -p "$(dirname "${OUTPUT_LIST}")"
    ( cd "${DROP_DIR}/cores" && ls -1 *_libretro.so 2>/dev/null ) | sort | \
        while read -r so; do excluded "${so%_libretro.so}" || echo "${so}"; done \
        > "${OUTPUT_LIST}"
fi

COUNT=$(grep -c '=y$' "${OUTPUT}" || true)
echo "[INFO] libretro-super: ${COUNT} core symbols exported to $(basename "${OUTPUT}")"

# Cores that ship but have no row: they land in /usr/lib/libretro and work when
# selected by hand, but es_systems.yml cannot reach them.  Listed rather than
# treated as an error -- most are cores knulli never packaged, so no symbol for
# them exists to put in the yml either.
UNMAPPED=""
for core in "${DROP_DIR}"/cores/*_libretro.so; do
    [ -e "$core" ] || continue
    bn=$(basename "$core")
    excluded "${bn%_libretro.so}" && continue
    grep -qE "^[[:space:]]*${bn//./\\.}[[:space:]]" "${CORES_SYMBOLS}" || UNMAPPED="${UNMAPPED} ${bn%_libretro.so}"
done
if [ -n "${UNMAPPED}" ]; then
    echo "[INFO] libretro-super: cores with no es_systems.yml symbol:${UNMAPPED}"
fi

if [ -n "${EXCLUDE}" ]; then
    echo "[INFO] libretro-super: cores excluded for this device: ${EXCLUDE}"
fi

exit 0
