#!/bin/bash

# We only want to run the script if the board has RGB capability
if ! knulli-board-capability "rgb"; then
    exit 1
fi

PERCENTAGE=$(knulli-battery-check capacity)

if [ ! -z "$PERCENTAGE" ] && [ ! -z "$1" ]; then
  curl -d "$PERCENTAGE $1" -X POST localhost:1235/update-battery-state
fi

exit 0
