# Profile: aarch64 / ARMv8.2-A / NEON+FP (mandatory) / LP64
#
# HOW (ABI + tuning + toolchain).  Says nothing about GPU or device: dist/ is
# keyed on the CPU/ABI profile so every device sharing this ISA level reuses the
# same artifacts.  See devices/*.device for who consumes it.
#
# Covers the knulli aarch64 targets whose cores are ARMv8.2-A:
#   a527/T527  Cortex-A55
#   rk3566     Cortex-A55
#   sm8250     Cortex-A76 + Cortex-A55
#
# ***** NOT INTERCHANGEABLE WITH aarch64-v8a. *****
# -mcpu=cortex-a55 raises the ISA level, not just the tuning: LSE atomics
# (ARMv8.1), fp16 arithmetic and dotprod (ARMv8.2) become available and GCC will
# emit them.  Those are UNDEFINED instructions on Cortex-A53/A35/A72/A73, so
# serving this dist/ to an aarch64-v8a device is a SIGILL, not a slowdown.
# The two dist/ trees must never be mixed.

ARCH_CLASS arm64

# Same Buildroot toolchain as aarch64-v8a (glibc 2.40, gcc 13.3, identical ABI);
# only the wrapper's -mcpu differs.

# Wrapper toolchain.  TOOLCHAIN_BIN is DERIVED from TOOLCHAIN_NAME
# (<repo>/toolchain-<name>/bin) and the wrapper itself is generated by
# gen-toolchain.sh from the keys below -- it is not a hand-maintained file.
# That is what lets a fresh checkout build: the old wrappers had the sysroot
# path baked in as a literal.
#
# ISA_FLAGS are PREPENDED by the wrapper, OPT_FLAGS APPENDED.  Nothing in a
# core Makefile sets the ISA, so it must be on every invocation; many cores
# tack on their own -O2 after their platform block, and for GCC the last -O
# wins, so appending is what makes -O3 actually stick.
TOOLCHAIN_NAME aarch64-v8.2a
CROSS_PREFIX aarch64-buildroot-linux-gnu-
ISA_FLAGS -mcpu=cortex-a55 -mtune=cortex-a55
OPT_FLAGS -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -fsigned-char -fdata-sections -ffunction-sections

# gcc 14 turned these long-standing C warnings into errors.  Every core here is
# an existing codebase that built for years under gcc <= 13, so demote them to
# warnings rather than patching each site: mame2003_xtreme alone hits atan2,
# flycast's bundled libzip hits close()/getpid(), yabause hits SH2DynShowSttaics.
# C only -- the gcc wrapper gets these, the g++ one does not.
C_ONLY_FLAGS -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -Wno-error=implicit-int -Wno-error=return-mismatch

# The REFERENCE board whose Buildroot sysroot this profile builds against.
# Named rather than inferred from whichever board happens to trigger the
# build first: the drop is shared by every board on this ABI, and the sysroot
# leaks into the ~6 GL-linking cores through the sonames they record.  For
# aarch64-v8a that matters concretely -- h700/rk3326/rk3576 are Mali and a133
# is PowerVR, so an a133-triggered build would hand PowerVR-linked cores to
# three Mali boards.  Fixing the reference makes the drop identical no matter
# who builds it.
SYSROOT_BOARD h700
# Emulators come from a board on this profile, not from h700: unlike a core,
# which is compiled with this profile's own ISA flags and merely borrows h700's
# sysroot, an emulator built on h700 would BE a v8a binary.  All three members
# have real Vulkan, so a527 costs nothing to prefer.
EMULATORS_BOARD a527
# Fallback for running the generators standalone in this tree; the knulli
# build passes --sysroot-bin instead, from SYSROOT_BOARD above.
SYSROOT_BIN /opt/fdata/knulli/knulli-linux/output/h700/host/bin
CC aarch64-v8.2a-gcc
CXX aarch64-v8.2a-g++
CXX11 aarch64-v8.2a-g++
CXX17 aarch64-v8.2a-g++
AR aarch64-buildroot-linux-gnu-ar
RANLIB aarch64-buildroot-linux-gnu-ranlib
STRIP aarch64-buildroot-linux-gnu-strip

PLATFORM unix

# HAVE_NEON absent for the same reason as aarch64-v8a: it gates ARM32 .S files.
EXTRA_ARGS HAS_GLES=1 FORCE_GLES=1

# Cross-cutting cmake flags, applied to every COMMAND=CMAKE core (per-core -D
# from coreargs comes after and wins).  The buildbot's own EXTRAARGS case has an
# empty default for platform=unix, so without the toolchain file cmake
# configures a NATIVE build and find_package resolves HOST libraries.
CMAKE_EXTRA_ARGS -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON

PATCH_TAGS aarch64 armv8 armv8.2 glesv2 buildroot

MAKEPORTABLE NO

# Build inputs.  Which core sets this profile builds, and the device-specific
# patch layer applied last (after _common and the PATCH_TAGS layers).
CORESETS tier1 tier2 tier3 tier4-cmake arm64-only
PATCH_SET aarch64-v8.2a

# What `uname -m` would report ON TARGET.  Cores under platform=unix derive
# their arch from the BUILD HOST (x86_64) and then emit x86 flags/asm; coreargs
# lines reference this as ${UNAME_M} to correct them per core.
UNAME_M aarch64
