# Profile: aarch64 / ARMv8.0-A baseline / NEON+FP (mandatory) / LP64
#
# HOW (ABI + tuning + toolchain).  Says nothing about GPU or device: dist/ is
# keyed on the CPU/ABI profile so every device sharing this ISA level reuses the
# same artifacts.  See devices/*.device for who consumes it.
#
# Covers every knulli aarch64 target whose cores are ARMv8.0-A:
#   h700    Cortex-A53
#   a133    Cortex-A53
#   rk3326  Cortex-A35
#   rk3576  Cortex-A72 + Cortex-A53   <- A72 is ARMv8.0-A, NOT v8.2
#   sd6115  Cortex-A73 + Cortex-A53   <- planned; A73 is also ARMv8.0-A
#
# -mcpu=cortex-a53 is the tuning choice, not an ISA gate: A53 is the most common
# core here and the one whose in-order pipeline benefits most from scheduling.
# The ISA level stays ARMv8.0-A, which every CPU above executes.

ARCH_CLASS arm64


# Wrapper toolchain.  TOOLCHAIN_BIN is DERIVED from TOOLCHAIN_NAME
# (<repo>/toolchain-<name>/bin) and the wrapper itself is generated by
# gen-toolchain.sh from the keys below -- it is not a hand-maintained file.
# That is what lets a fresh checkout build: the old wrappers had the sysroot
# path baked in as a literal.
#
# ISA_FLAGS are PREPENDED by the wrapper, OPT_FLAGS APPENDED.  Nothing in a
# core Makefile sets the ISA, so it must be on every invocation; many cores
# tack on their own -O2 after their platform block, and for GCC the last -O
# wins, so appending is what makes -O3 actually stick.
TOOLCHAIN_NAME aarch64-v8a
CROSS_PREFIX aarch64-buildroot-linux-gnu-
ISA_FLAGS -mcpu=cortex-a53 -mtune=cortex-a53
OPT_FLAGS -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -fsigned-char -fdata-sections -ffunction-sections

# gcc 14 turned these long-standing C warnings into errors.  Every core here is
# an existing codebase that built for years under gcc <= 13, so demote them to
# warnings rather than patching each site: mame2003_xtreme alone hits atan2,
# flycast's bundled libzip hits close()/getpid(), yabause hits SH2DynShowSttaics.
# C only -- the gcc wrapper gets these, the g++ one does not.
C_ONLY_FLAGS -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -Wno-error=implicit-int -Wno-error=return-mismatch

# The REFERENCE board whose Buildroot sysroot this profile builds against.
# Named rather than inferred from whichever board happens to trigger the
# build first: the drop is shared by every board on this ABI, and the sysroot
# leaks into the ~6 GL-linking cores through the sonames they record.  For
# aarch64-v8a that matters concretely -- h700/rk3326/rk3576 are Mali and a133
# is PowerVR, so an a133-triggered build would hand PowerVR-linked cores to
# three Mali boards.  Fixing the reference makes the drop identical no matter
# who builds it.
SYSROOT_BOARD h700
# Which board builds the standalone emulator drop for this profile.  Separate
# from SYSROOT_BOARD because the two builders want different things: cores need
# a sysroot to link against, emulators need the richest capability set on the
# ABI, since a capability compiled out cannot be restored per board.  rk3576 is
# Mali like most of the profile and the only member with real Vulkan.
EMULATORS_BOARD rk3576
EMULATORS_BOARD_POWERVR a133
# Fallback for running the generators standalone in this tree; the knulli
# build passes --sysroot-bin instead, from SYSROOT_BOARD above.
SYSROOT_BIN /opt/fdata/knulli/knulli-linux/output/h700/host/bin
CC aarch64-v8a-gcc
CXX aarch64-v8a-g++
CXX11 aarch64-v8a-g++
CXX17 aarch64-v8a-g++
AR aarch64-buildroot-linux-gnu-ar
RANLIB aarch64-buildroot-linux-gnu-ranlib
STRIP aarch64-buildroot-linux-gnu-strip

# platform=unix is what the cores' Makefiles actually match on; no composite
# armv-* string exists for aarch64 upstream.  Measured 51/57 vs 25/57 on armv7.
PLATFORM unix

# HAVE_NEON is deliberately ABSENT.  On aarch64 it gates ARM32 .S files
# (libretro-common/audio/*_neon.S is armv7 assembly) and setting it breaks the
# assemble step.  Cores wanting ARMv8 SIMD detect __ARM_NEON themselves.
EXTRA_ARGS HAS_GLES=1 FORCE_GLES=1

# Cross-cutting cmake flags, applied to every COMMAND=CMAKE core (per-core -D
# from coreargs comes after and wins).  The buildbot's own EXTRAARGS case has an
# empty default for platform=unix, so without the toolchain file cmake
# configures a NATIVE build and find_package resolves HOST libraries.
CMAKE_EXTRA_ARGS -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON

PATCH_TAGS aarch64 armv8 glesv2 buildroot

MAKEPORTABLE NO

# Build inputs.  Which core sets this profile builds, and the device-specific
# patch layer applied last (after _common and the PATCH_TAGS layers).
CORESETS tier1 tier2 tier3 tier4-cmake arm64-only
PATCH_SET aarch64-v8a

# What `uname -m` would report ON TARGET.  Cores under platform=unix derive
# their arch from the BUILD HOST (x86_64) and then emit x86 flags/asm; coreargs
# lines reference this as ${UNAME_M} to correct them per core.
UNAME_M aarch64
