# Profile: armv7 / Cortex-A9 / NEONv1 / VFPv3 / hard-float
#
# HOW (ABI + tuning + toolchain).  Deliberately says nothing about GPU or device:
# dist/ is keyed on the CPU/ABI profile so every device sharing this ABI reuses
# the same artifacts.  See devices/*.device for who consumes it.
#
# Covers: Actions ATM7051, Actions ATM7039 (knulli target atm7039).
# Both are quad Cortex-A9, ARMv7-A, NEONv1/VFPv3, EABIhf.

ARCH_CLASS arm32

# Toolchain.  The wrapper PREPENDS ISA/ABI flags and APPENDS the -O profile;
# env CFLAGS loses to a Makefile's own "CFLAGS =", and several cores tack on
# -O2 after their platform block (last -O wins).  See toolchain-atm7051/bin/.

# Wrapper toolchain.  TOOLCHAIN_BIN is DERIVED from TOOLCHAIN_NAME
# (<repo>/toolchain-<name>/bin) and the wrapper itself is generated by
# gen-toolchain.sh from the keys below -- it is not a hand-maintained file.
# That is what lets a fresh checkout build: the old wrappers had the sysroot
# path baked in as a literal.
#
# ISA_FLAGS are PREPENDED by the wrapper, OPT_FLAGS APPENDED.  Nothing in a
# core Makefile sets the ISA, so it must be on every invocation; many cores
# tack on their own -O2 after their platform block, and for GCC the last -O
# wins, so appending is what makes -O3 actually stick.
TOOLCHAIN_NAME atm7051
CROSS_PREFIX arm-buildroot-linux-gnueabihf-
ISA_FLAGS -marm -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=neon -mfloat-abi=hard
OPT_FLAGS -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -fsigned-char -fdata-sections -ffunction-sections

# gcc 14 turned these long-standing C warnings into errors.  Every core here is
# an existing codebase that built for years under gcc <= 13, so demote them to
# warnings rather than patching each site: mame2003_xtreme alone hits atan2,
# flycast's bundled libzip hits close()/getpid(), yabause hits SH2DynShowSttaics.
# C only -- the gcc wrapper gets these, the g++ one does not.
C_ONLY_FLAGS -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -Wno-error=implicit-int -Wno-error=return-mismatch

# Force-included into every TU.  This sysroot's kernel headers predate the
# ARMv8 crypto/CRC HWCAP2 bits that vendored LZMA CpuArch.c probes for.
COMPAT_HEADER compat-atm7051.h

# The REFERENCE board whose Buildroot sysroot this profile builds against.
# Named rather than inferred from whichever board happens to trigger the
# build first: the drop is shared by every board on this ABI, and the sysroot
# leaks into the ~6 GL-linking cores through the sonames they record.  For
# aarch64-v8a that matters concretely -- h700/rk3326/rk3576 are Mali and a133
# is PowerVR, so an a133-triggered build would hand PowerVR-linked cores to
# three Mali boards.  Fixing the reference makes the drop identical no matter
# who builds it.
SYSROOT_BOARD atm7039
# Fallback for running the generators standalone in this tree; the knulli
# build passes --sysroot-bin instead, from SYSROOT_BOARD above.
SYSROOT_BIN /opt/fdata/knulli/knulli-linux/output/atm7039/host/bin
CC atm7051-gcc
CXX atm7051-g++
CXX11 atm7051-g++
CXX17 atm7051-g++
AR arm-buildroot-linux-gnueabihf-ar
RANLIB arm-buildroot-linux-gnueabihf-ranlib
STRIP arm-buildroot-linux-gnueabihf-strip

# platform=unix is the tested default, NOT a composite armv-* string.
# Measured over the 57-core tier1 set: unix -> 51/57, armv-neon-cortexa9-hardfloat -> 25/57.
# Composite strings break cores matching `ifeq ($(platform), unix)` exactly (they fall
# through to the MinGW default and link a .dll), and some armv branches hardcode CC=gcc.
# Opt into the composite string PER CORE via coreargs/, never globally.
PLATFORM unix

# Cross-cutting args.  HAVE_NEON=1: the wrapper always passes -mfpu=neon so
# libretro-common's C takes its NEON path, but each Makefile gates assembling the
# matching .S on HAVE_NEON (default 0) -> undefined convert_float_s16_asm.
# HAS_GLES/FORCE_GLES: optional-GL cores otherwise default to desktop GL.
EXTRA_ARGS HAVE_NEON=1 HAS_GLES=1 FORCE_GLES=1

# Cross-cutting cmake flags, applied to every COMMAND=CMAKE core (per-core -D
# from coreargs comes after and wins).  The buildbot's own EXTRAARGS case has an
# empty default for platform=unix, so without the toolchain file cmake
# configures a NATIVE build and find_package resolves HOST libraries.
CMAKE_EXTRA_ARGS -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON

PATCH_TAGS armv7 neon cortex-a9 glesv2 buildroot

# retrolink.sh byte-patches .so files for ancient-glibc symbol versioning:
# pointless against a Buildroot sysroot.
MAKEPORTABLE NO

# Build inputs.  Which core sets this profile builds, and the device-specific
# patch layer applied last (after _common and the PATCH_TAGS layers).
CORESETS tier1 tier2 tier3 tier4-cmake
PATCH_SET armv7-neon-cortexa9-hf

# See aarch64-v8a.profile: target `uname -m`, referenced by coreargs as ${UNAME_M}.
UNAME_M armv7l
