# Profile: armv7 / Cortex-A7 / NEON-VFPv4 / hard-float
#
# HOW (ABI + tuning + toolchain).  Says nothing about GPU or device: dist/ is
# keyed on the CPU/ABI profile so every device sharing this ABI reuses the same
# artifacts.  See devices/*.device for who consumes it.
#
# Covers: Allwinner R16/A33 (knulli target r16), Rockchip RK3128.
# Both are quad Cortex-A7, ARMv7-A, NEON-VFPv4, EABIhf.  Both are Mali-400
# (GLESv2 only) parts, but that is a device fact, not an ABI fact.
#
# Distinct from armv7-neon-cortexa9-hf: A7 has VFPv4 (fused multiply-add,
# hardware divide) where A9 has only VFPv3.  A VFPv4-built binary traps on A9.

ARCH_CLASS arm32

# Toolchain: rk3128's Buildroot output (gcc 13.3, glibc 2.40).
#
# NOTE ON r16: knulli-r16.board pinned BR2_GCC_VERSION_12_X=y, giving r16 a
# libstdc++ capped at GLIBCXX_3.4.30 while rk3128/h700 are at 3.4.32.  Any C++
# core built here needs 3.4.32 and would fail to load on such an r16 image.
# The pin has been removed from knulli-r16.board; r16 needs a from-scratch
# rebuild before it can consume this dist/.

# Wrapper toolchain.  TOOLCHAIN_BIN is DERIVED from TOOLCHAIN_NAME
# (<repo>/toolchain-<name>/bin) and the wrapper itself is generated by
# gen-toolchain.sh from the keys below -- it is not a hand-maintained file.
# That is what lets a fresh checkout build: the old wrappers had the sysroot
# path baked in as a literal.
#
# ISA_FLAGS are PREPENDED by the wrapper, OPT_FLAGS APPENDED.  Nothing in a
# core Makefile sets the ISA, so it must be on every invocation; many cores
# tack on their own -O2 after their platform block, and for GCC the last -O
# wins, so appending is what makes -O3 actually stick.
TOOLCHAIN_NAME armv7-a7
CROSS_PREFIX arm-buildroot-linux-gnueabihf-
ISA_FLAGS -marm -mcpu=cortex-a7 -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard
OPT_FLAGS -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -fsigned-char -fdata-sections -ffunction-sections

# gcc 14 turned these long-standing C warnings into errors.  Every core here is
# an existing codebase that built for years under gcc <= 13, so demote them to
# warnings rather than patching each site: mame2003_xtreme alone hits atan2,
# flycast's bundled libzip hits close()/getpid(), yabause hits SH2DynShowSttaics.
# C only -- the gcc wrapper gets these, the g++ one does not.
C_ONLY_FLAGS -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -Wno-error=implicit-int -Wno-error=return-mismatch

# The REFERENCE board whose Buildroot sysroot this profile builds against.
# Named rather than inferred from whichever board happens to trigger the
# build first: the drop is shared by every board on this ABI, and the sysroot
# leaks into the ~6 GL-linking cores through the sonames they record.  For
# aarch64-v8a that matters concretely -- h700/rk3326/rk3576 are Mali and a133
# is PowerVR, so an a133-triggered build would hand PowerVR-linked cores to
# three Mali boards.  Fixing the reference makes the drop identical no matter
# who builds it.
SYSROOT_BOARD rk3128
# Fallback for running the generators standalone in this tree; the knulli
# build passes --sysroot-bin instead, from SYSROOT_BOARD above.
SYSROOT_BIN /opt/fdata/knulli/knulli-linux/output/rk3128/host/bin
CC armv7-a7-gcc
CXX armv7-a7-g++
CXX11 armv7-a7-g++
CXX17 armv7-a7-g++
AR arm-buildroot-linux-gnueabihf-ar
RANLIB arm-buildroot-linux-gnueabihf-ranlib
STRIP arm-buildroot-linux-gnueabihf-strip

# platform=unix is the tested default, NOT a composite armv-* string.
# Measured over the 57-core tier1 set: unix -> 51/57, composite -> 25/57.
PLATFORM unix

# HAVE_NEON=1: the wrapper always passes -mfpu=neon-vfpv4 so libretro-common's C
# takes its NEON path, but each Makefile gates assembling the matching .S on
# HAVE_NEON (default 0) -> undefined convert_float_s16_asm.
EXTRA_ARGS HAVE_NEON=1 HAS_GLES=1 FORCE_GLES=1

# Cross-cutting cmake flags, applied to every COMMAND=CMAKE core (per-core -D
# from coreargs comes after and wins).  The buildbot's own EXTRAARGS case has an
# empty default for platform=unix, so without the toolchain file cmake
# configures a NATIVE build and find_package resolves HOST libraries.
CMAKE_EXTRA_ARGS -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON

PATCH_TAGS armv7 neon cortex-a7 glesv2 buildroot

MAKEPORTABLE NO

# Build inputs.  Which core sets this profile builds, and the device-specific
# patch layer applied last (after _common and the PATCH_TAGS layers).
CORESETS tier1 tier2 tier3 tier4-cmake
PATCH_SET armv7-neon-cortexa7-hf

# See aarch64-v8a.profile: target `uname -m`, referenced by coreargs as ${UNAME_M}.
UNAME_M armv7l
