#!/usr/bin/env python3
"""
Knulli OTA Update Publisher

Reads build artifacts from a completed buildroot output directory, merges the
new firmware data into updates.json, uploads all changed files to the update
server via SCP, and triggers a hot-reload.

Directory layout expected under --output-dir (e.g. output/h700):
  images/rootfs.squashfs
  images/knulli/images/{board}/firmware.sig   ← one per board variant
  images/knulli/boot_{board}/                 ← assembled boot FAT per board
  updates/patches/{from}_to_{to}.patch        ← generated by post-image-script.sh
  releases/{md5}_rootfs.squashfs              ← previous rootfs kept for delta gen

Usage:
  publish_update.py --output-dir output/h700 --channel alpha \\
                    --updates-json update_server/updates.knulli.org/updates.json \\
                    --base-url https://updates.example.org \\
                    --ssh-host updates.example.org --ssh-user myuser \\
                    --ssh-key ~/.ssh/build_key [--admin-key KEY] [--yes]
"""

import argparse
import copy
import json
import os
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# firmware.sig parser
# ---------------------------------------------------------------------------

def parse_firmware_sig(sig_path):
    """Parse an INI-style firmware.sig file.

    Returns a dict with keys 'metadata' and 'partitions', each a flat dict.
    """
    result = {"metadata": {}, "partitions": {}}
    section = None
    with open(sig_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("[") and line.endswith("]"):
                section = line[1:-1]
                continue
            if section and "=" in line:
                key, _, value = line.partition("=")
                result.setdefault(section, {})[key.strip()] = value.strip().strip('"')
    return result


def is_allwinner_bsp(partitions):
    """Return True if this firmware.sig is from an Allwinner BSP board.

    Detection: presence of boot0.img_md5 that is not MISSING.
    """
    return partitions.get("boot0.img_md5", "MISSING") != "MISSING"


# ---------------------------------------------------------------------------
# Build info collection
# ---------------------------------------------------------------------------

def collect_subtargets(output_dir):
    """Walk images/knulli/images/ and return a list of (board, sig_dict, boot_dir).

    boot_dir is the path to the assembled boot FAT for this board variant,
    or None if it doesn't exist (e.g. Allwinner BSP boards where boot files
    are not tracked individually).
    """
    images_dir = output_dir / "images" / "knulli" / "images"
    if not images_dir.is_dir():
        print(f"ERROR: {images_dir} not found — run the build first", file=sys.stderr)
        sys.exit(1)

    subtargets = []
    for sub in sorted(images_dir.iterdir()):
        sig_path = sub / "firmware.sig"
        if not sig_path.exists():
            continue
        sig = parse_firmware_sig(sig_path)
        board = sig["metadata"].get("board", sub.name)
        if sig["metadata"].get("arch", "unknown") == "unknown":
            sig["metadata"]["arch"] = output_dir.name
        boot_dir = output_dir / "images" / "knulli" / f"boot_{board}"
        subtargets.append((board, sig, boot_dir if boot_dir.is_dir() else None))

    if not subtargets:
        print("ERROR: No firmware.sig files found — nothing to publish", file=sys.stderr)
        sys.exit(1)

    return subtargets


# ---------------------------------------------------------------------------
# updates.json merge
# ---------------------------------------------------------------------------

def build_rootfs_entry(sig, channel, base_url):
    """Build the rootfs 'current' dict for this build."""
    p = sig["partitions"]
    m = sig["metadata"]
    md5 = p["rootfs.squashfs_md5"]
    arch = m.get("arch", "unknown")
    return arch, {
        "md5": md5,
        "url": f"{base_url}/rootfs/{channel}/rootfs_{md5}.squashfs",
        "version": m.get("version", "unknown"),
        "build_date": m.get("build_date", datetime.now().isoformat()),
        "size": int(p.get("rootfs.squashfs_size", 0)),
    }


def collect_patches(patches_dir, target_md5, base_url):
    """Scan patches_dir for files ending in _to_{target_md5}.patch and return
    a dict of {from_md5: {target_md5, url}} entries to merge."""
    entries = {}
    if not patches_dir.is_dir():
        return entries
    suffix = f"_to_{target_md5}.patch"
    for patch_file in patches_dir.glob(f"*{suffix}"):
        from_md5 = patch_file.name[: -len(suffix)]
        if from_md5:
            entries[from_md5] = {
                "target_md5": target_md5,
                "url": f"{base_url}/updates/patches/{patch_file.name}",
            }
    return entries


def merge_updates(current, subtargets, channel, base_url, patches_dir):
    """Merge build data into a deep copy of current updates.json.

    Returns (updated_dict, summary) where summary is a list of human-readable
    change descriptions.
    """
    updated = copy.deepcopy(current)
    summary = []

    # Ensure top-level keys exist
    updated.setdefault("rootfs", {}).setdefault(channel, {})
    updated.setdefault("devices", {}).setdefault(channel, {})
    updated.setdefault("boot_files", {}).setdefault(channel, {})

    rootfs_done = set()  # (arch,) — rootfs is shared per arch, only update once

    for board, sig, boot_dir in subtargets:
        m = sig["metadata"]
        p = sig["partitions"]
        arch = m.get("arch", "unknown")

        # --- rootfs (shared per arch) ---
        if arch not in rootfs_done:
            arch_entry, new_current = build_rootfs_entry(sig, channel, base_url)
            old_current = updated["rootfs"][channel].get(arch, {}).get("current", {})

            if old_current.get("md5") != new_current["md5"]:
                summary.append(
                    f"rootfs [{arch}]: {old_current.get('md5', 'none')[:8]}… → {new_current['md5'][:8]}… "
                    f"({m.get('version', '?')})"
                )
            else:
                summary.append(f"rootfs [{arch}]: unchanged ({new_current['md5'][:8]}…)")

            updated["rootfs"][channel].setdefault(arch, {})["current"] = new_current

            # Merge patches (accumulate — never remove old entries)
            new_patches = collect_patches(patches_dir, new_current["md5"], base_url)
            updated["rootfs"][channel][arch].setdefault("patches", {}).update(new_patches)
            if new_patches:
                summary.append(f"  patches [{arch}]: +{len(new_patches)} new entry/entries")

            rootfs_done.add(arch)

        # --- Allwinner BSP: partition images (boot0.img, etc.) ---
        # NOTE: partition MD5s are intentionally NOT written to updated["devices"] here.
        # They are applied in main() only after the source file is confirmed to exist
        # in the upload plan, preventing phantom MD5 updates when a file can't be found.

        # --- Boot-FAT platforms: kernel, DTBs, boot config ---
        else:
            ch_boot = updated["boot_files"][channel]
            for key, value in p.items():
                if not key.endswith("_md5") or key == "rootfs.squashfs_md5":
                    continue
                file_key = key[: -len("_md5")]
                path = p.get(f"{file_key}_path")
                size = int(p.get(f"{file_key}_size", 0))
                if not path or not value or value == "MISSING":
                    continue
                url = f"{base_url}/updates/boot_files/{arch}/{channel}/{board}/{file_key}"
                old_entry = ch_boot.get(file_key, {}).get(board, {})
                new_entry = {"target_md5": value, "path": path, "url": url, "size": size}
                ch_boot.setdefault(file_key, {})[board] = new_entry
                if old_entry.get("target_md5") != value:
                    summary.append(
                        f"  boot_file [{board}] {file_key}: "
                        f"{old_entry.get('target_md5', 'none')[:8]}… → {value[:8]}…"
                    )

    return updated, summary


# ---------------------------------------------------------------------------
# File upload plan
# ---------------------------------------------------------------------------

def check_baselines_exist(subtargets, releases_dir):
    """Abort if any arch's current rootfs has not been saved as a baseline.

    This enforces the rule: save_baseline.py must be run before publish_update.py
    so that every published version can serve as a delta source for future builds.
    """
    missing = []
    seen_archs = set()
    for board, sig, _boot_dir in subtargets:
        arch    = sig["metadata"].get("arch", "unknown")
        new_md5 = sig["partitions"].get("rootfs.squashfs_md5", "MISSING")
        if arch in seen_archs or new_md5 == "MISSING":
            continue
        seen_archs.add(arch)
        baseline_file = releases_dir / arch / f"{new_md5}_rootfs.squashfs"
        if not baseline_file.exists():
            missing.append((arch, new_md5, baseline_file))

    if missing:
        print("ERROR: The following rootfs files have not been baselined:", file=sys.stderr)
        for arch, md5, path in missing:
            print(f"  [{arch}] {md5[:8]}… — expected at {path}", file=sys.stderr)
        print("Run save_baseline.py first, then re-run this script.", file=sys.stderr)
        sys.exit(1)


def build_upload_plan(subtargets, output_dir, channel, updated, base_url, current_updates, baseline_dir=None, force_partitions=False):
    """Return (upload_list, partition_md5_updates).

    upload_list: list of (local_path, remote_rel_path) to upload via SCP.
    partition_md5_updates: dict {(board, part): md5} for Allwinner partition
        files that are confirmed to have a source and will be uploaded.
        Applied to updated_updates in main() AFTER the plan is built, so that
        partition MD5s are never written to updates.json unless the file exists.

    Deduplicates by remote path. Boot/partition files are skipped when their
    MD5 already matches what is recorded in the pre-merge updates.json.
    """
    plan = {}  # remote_rel_path → local_path
    partition_md5_updates = {}  # (board, part) → md5

    patches_dir = output_dir / "updates" / "patches"

    for board, sig, boot_dir in subtargets:
        m = sig["metadata"]
        p = sig["partitions"]
        arch = m.get("arch", "unknown")

        # patches that target the new rootfs MD5 — skip if already recorded
        new_md5 = p["rootfs.squashfs_md5"]
        prev_patches = (current_updates
                        .get("rootfs", {})
                        .get(channel, {})
                        .get(arch, {})
                        .get("patches", {}))
        if patches_dir.is_dir():
            suffix = f"_to_{new_md5}.patch"
            for patch in patches_dir.glob(f"*{suffix}"):
                from_md5 = patch.name[: -len(suffix)]
                if prev_patches.get(from_md5, {}).get("target_md5") == new_md5:
                    continue  # this exact from→to patch already on server
                remote = f"updates/patches/{patch.name}"
                plan[remote] = patch

        # Allwinner BSP: upload partition images when their MD5 has changed.
        # Source priority: baseline_dir copy → build-output path (boot_package.fex only).
        # boot0.img / boot.img / env.img are static source-tree files only available
        # via baseline_dir; boot_package.fex is always findable in the build output.
        #
        # We compare against current_updates (pre-merge state) NOT the merged dict,
        # because partition MD5s are only written to updates.json in main() after a
        # source file is confirmed to exist — preventing phantom MD5 updates where
        # updates.json advances past what the server actually has.
        if is_allwinner_bsp(p):
            partitions_baseline = (baseline_dir / "updates" / "partitions" / board
                                   if baseline_dir else None)
            prev_devices = (current_updates
                            .get("devices", {})
                            .get(channel, {}))
            for part in ("boot0.img", "boot_package.fex", "boot.img", "env.img"):
                new_part_md5 = p.get(f"{part}_md5", "MISSING")
                if new_part_md5 == "MISSING":
                    continue
                prev_md5 = prev_devices.get(part, {}).get(board)
                if prev_md5 == new_part_md5 and not force_partitions:
                    continue  # server already has this version
                # Resolve source file
                local = None
                if partitions_baseline:
                    candidate = partitions_baseline / part
                    if candidate.exists():
                        local = candidate
                if local is None and part == "boot_package.fex":
                    # h700/a133: built per-board into images/{arch}-boot-packages/
                    # a527 and similar: static source-tree file; not accessible here
                    # without --source-dir, but will be in baseline after save_baseline.py
                    candidate = output_dir / "images" / f"{arch}-boot-packages" / f"{board}_{part}"
                    if candidate.exists():
                        local = candidate
                if local is not None:
                    remote = f"updates/partitions/{board}/{channel}/{part}"
                    plan[remote] = local
                    partition_md5_updates[(board, part)] = new_part_md5
                else:
                    print(f"  WARNING: {board}/{part}: source file not found — "
                          f"provide --baseline-dir to upload this file", file=sys.stderr)

        # Boot-FAT platforms: upload each tracked boot file, but only if its
        # MD5 differs from what was already stored in updates.json before this run
        if not is_allwinner_bsp(p) and boot_dir:
            prev_boot_files = (current_updates
                               .get("boot_files", {})
                               .get(channel, {}))
            for key, value in p.items():
                if not key.endswith("_md5") or key == "rootfs.squashfs_md5":
                    continue
                file_key = key[: -len("_md5")]
                fat_path = p.get(f"{file_key}_path")
                if not fat_path or not value or value == "MISSING":
                    continue
                prev_md5 = (prev_boot_files
                            .get(file_key, {})
                            .get(board, {})
                            .get("target_md5"))
                if prev_md5 == value:
                    continue  # already on server with this MD5
                local = boot_dir / fat_path
                if local.exists():
                    remote = f"updates/boot_files/{arch}/{channel}/{board}/{file_key}"
                    plan[remote] = local

    return list(plan.items()), partition_md5_updates


# ---------------------------------------------------------------------------
# SCP helpers
# ---------------------------------------------------------------------------

def scp_file(local_path, remote_rel_path, ssh_host, ssh_user, ssh_key, ssh_home, ssh_port=22):
    """Upload a single file via SCP. Creates the remote directory if needed."""
    remote_dir = str(Path(ssh_home) / Path(remote_rel_path).parent)
    remote_full = f"{ssh_user}@{ssh_host}:{ssh_home}/{remote_rel_path}"
    port_str = str(ssh_port)

    # Ensure the remote directory exists
    subprocess.run(
        ["ssh", "-i", ssh_key, "-p", port_str, "-o", "StrictHostKeyChecking=accept-new",
         f"{ssh_user}@{ssh_host}", f"mkdir -p {remote_dir}"],
        check=True, capture_output=True
    )

    result = subprocess.run(
        ["scp", "-i", ssh_key, "-P", port_str, "-o", "StrictHostKeyChecking=accept-new",
         str(local_path), remote_full],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr.strip()}", file=sys.stderr)
        return False
    return True


def trigger_reload(server_url, admin_key=None):
    """POST to /admin/reload to hot-reload the update server."""
    try:
        import urllib.request
        req = urllib.request.Request(
            f"{server_url}/admin/reload",
            data=b"",
            method="POST"
        )
        if admin_key:
            req.add_header("X-Admin-Key", admin_key)
        with urllib.request.urlopen(req, timeout=15) as resp:
            body = resp.read().decode()
            print(f"  Server reload: {resp.status} {body[:120]}")
            return resp.status == 200
    except Exception as e:
        print(f"  WARNING: reload request failed: {e}", file=sys.stderr)
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Publish a Knulli build to the OTA update server."
    )
    parser.add_argument(
        "--output-dir", required=True,
        help="Buildroot output directory for this arch (e.g. output/h700)"
    )
    parser.add_argument(
        "--channel", required=True, choices=["stable", "alpha", "dev"],
        help="Update channel to publish to"
    )
    parser.add_argument(
        "--updates-json", required=True,
        help="Path to the local updates.json to read and update"
    )
    parser.add_argument(
        "--baseline-dir",
        help="Baseline storage directory (same as used with save_baseline.py). "
             "When provided, the script verifies each arch's rootfs is baselined "
             "before publishing and reads patches from there instead of output-dir."
    )
    parser.add_argument(
        "--base-url", required=True,
        help="Public base URL of the update server (e.g. https://updates.example.org)"
    )
    parser.add_argument(
        "--ssh-host", required=True,
        help="SSH hostname of the update server"
    )
    parser.add_argument(
        "--ssh-user", required=True,
        help="SSH username on the update server"
    )
    parser.add_argument(
        "--ssh-key", required=True,
        help="Path to the SSH private key for passwordless SCP"
    )
    parser.add_argument(
        "--ssh-home", required=True,
        help="Remote web-root directory on the server (e.g. public_html or the domain folder)"
    )
    parser.add_argument(
        "--ssh-port", type=int, default=22,
        help="SSH port on the update server (default: 22)"
    )
    parser.add_argument(
        "--admin-key",
        help="Admin key for the /admin/reload endpoint (optional)"
    )
    parser.add_argument(
        "--yes", "-y", action="store_true",
        help="Skip confirmation prompt and proceed immediately"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be uploaded/changed without doing anything"
    )
    parser.add_argument(
        "--force-partitions", action="store_true",
        help="Re-upload Allwinner BSP partition files even if updates.json already "
             "records the same MD5 (use when a previous run updated updates.json "
             "without actually uploading the files)"
    )

    args = parser.parse_args()

    output_dir = Path(args.output_dir).resolve()
    updates_json_path = Path(args.updates_json).resolve()
    ssh_key = str(Path(args.ssh_key).expanduser())

    baseline_dir = Path(args.baseline_dir).resolve() if args.baseline_dir else None
    releases_dir = baseline_dir / "releases" if baseline_dir else None
    patches_dir  = (baseline_dir / "updates" / "patches") if baseline_dir \
                   else (output_dir / "updates" / "patches")

    # --- Load current updates.json ---
    print(f"Loading {updates_json_path}")
    with open(updates_json_path, "r") as f:
        current_updates = json.load(f)

    # --- Collect build info ---
    print(f"Scanning {output_dir}/images/knulli/images/ ...")
    subtargets = collect_subtargets(output_dir)
    print(f"  Found {len(subtargets)} board variant(s): {', '.join(b for b, _, _ in subtargets)}")

    # --- Preflight: verify baselines exist before touching anything ---
    if releases_dir:
        check_baselines_exist(subtargets, releases_dir)

    # --- Merge (rootfs, patches, boot_files — NOT Allwinner partition MD5s yet) ---
    updated_updates, summary = merge_updates(
        current_updates, subtargets, args.channel, args.base_url, patches_dir
    )

    # --- Upload plan + confirmed partition MD5 updates ---
    upload_plan, partition_md5_updates = build_upload_plan(
        subtargets, output_dir, args.channel, updated_updates, args.base_url, current_updates,
        baseline_dir=baseline_dir, force_partitions=args.force_partitions
    )

    # Apply partition MD5 updates only for files that have a confirmed source.
    # This prevents updates.json from advancing past what's actually on the server.
    updated_updates.setdefault("devices", {}).setdefault(args.channel, {})
    for (board, part), md5 in partition_md5_updates.items():
        old_md5 = current_updates.get("devices", {}).get(args.channel, {}).get(part, {}).get(board)
        updated_updates["devices"][args.channel].setdefault(part, {})[board] = md5
        if old_md5 != md5:
            summary.append(f"  partition [{board}] {part}: {(old_md5 or 'none')[:8]}… → {md5[:8]}…")

    # --- Show summary ---
    print()
    print(f"=== Changes for channel '{args.channel}' ===")
    for line in summary:
        print(f"  {line}")

    print()
    print(f"=== Files to upload ({len(upload_plan)}) ===")
    for remote, local in upload_plan:
        size_mb = local.stat().st_size / 1024 / 1024 if local.exists() else 0
        print(f"  {local.name:45s} → {remote}  ({size_mb:.1f} MB)")
    print(f"  updates.json                                  → {args.ssh_home}/updates.json")

    if args.dry_run:
        print()
        print("Dry run — nothing uploaded.")
        return 0

    # --- Confirm ---
    if not args.yes:
        print()
        try:
            answer = input("Proceed? [y/N] ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nAborted.")
            return 1
        if answer != "y":
            print("Aborted.")
            return 1

    # --- Upload files ---
    print()
    print("Uploading files...")
    failed = []
    for remote, local in upload_plan:
        if not local.exists():
            print(f"  SKIP (missing): {local}")
            continue
        print(f"  {local.name} → {remote}")
        if not scp_file(local, remote, args.ssh_host, args.ssh_user, ssh_key, args.ssh_home, args.ssh_port):
            failed.append(remote)

    if failed:
        print(f"\nERROR: {len(failed)} upload(s) failed:")
        for f in failed:
            print(f"  {f}")
        print("updates.json NOT uploaded — fix the errors above and retry.")
        return 1

    # --- Write and upload updates.json ---
    print()
    print("Writing updated updates.json...")
    # Write to a temp file then SCP atomically
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False, prefix="updates_"
    ) as tmp:
        json.dump(updated_updates, tmp, indent=2)
        tmp_path = tmp.name

    try:
        # Also save locally (overwrite the source file)
        with open(updates_json_path, "w") as f:
            json.dump(updated_updates, f, indent=2)
        print(f"  Saved locally: {updates_json_path}")

        print(f"  Uploading to {args.ssh_home}/updates.json ...")
        if not scp_file(Path(tmp_path), "updates.json", args.ssh_host, args.ssh_user, ssh_key, args.ssh_home, args.ssh_port):
            print("ERROR: Failed to upload updates.json", file=sys.stderr)
            return 1
    finally:
        os.unlink(tmp_path)

    # --- Hot-reload the server ---
    print()
    print("Triggering server reload...")
    trigger_reload(args.base_url, args.admin_key)

    print()
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
