#!/bin/sh

mount -t proc  -o nodev,noexec,nosuid proc  /proc   
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys    
mount -t devtmpfs none /dev

exec < /dev/console > /dev/console 2>&1

mount -o rw,remount /
mkdir -p /run /var/run/ /dev/pts /dev/shm

exec /sbin/init

