#!/bin/sh

BIN="/usr/bin/trimui_inputd"
[ -f "$BIN" ] || exit 0

BOARD=$(cat /boot/boot/knulli.board)
if [ "$BOARD" != "trimui-smart-pro" ] && [ "$BOARD" != "trimui-brick" ]; then
        exit 0
fi

case "$1" in
    start)
        "$BIN" &
        ;;
    stop)
        killall -9 trimui_inputd 2>/dev/null || true
        ;;
esac

exit 0

