#!/bin/sh

BOARD=$(cat /boot/boot/knulli.board)

case $1 in
    start)
	if [ "$BOARD" = "trimui-smart-pro" ]; then 
		trimui_inputd_smart_pro &
	elif [ "$BOARD" = "trimui-brick" ] || [ "$BOARD" = "magicx-zero-40"]; then
		trimui_inputd_brick &
	fi
	;;
     stop)
	killall -9 trimui_inputd_smart_pro
	killall -9 trimui_inputd_brick
	;;
esac

exit 0

