#!/bin/bash

BATTSAVER_DIR="/var/run/battery-saver/"
mkdir -p "$BATTSAVER_DIR"

GOVERNOR_SAVED="/var/run/battery-saver/governor.saved"
GOVERNOR=""

MODE="$(/usr/bin/knulli-settings-get system.batterysaver.mode)"

AGGRESSIVE="$(/usr/bin/knulli-settings-get system.batterysaver.aggressive)"

MUTE="$(/usr/bin/knulli-settings-get system.batterysaver.mute)"

undo_aggressive() {
  knulli-aggressive-saver off
}

do_active() {
    case "$MODE" in
        dim)
            [[ "${AGGRESSIVE:-0}" == "1" ]] && undo_aggressive

            [[ "$MUTE" == "1" ]] && knulli-audio setSystemVolume unmute
            knulli-brightness undim
        ;;
        dispoff)
            [[ "${AGGRESSIVE:-0}" == "1" ]] && undo_aggressive

            knulli-brightness dispon
            [[ "$MUTE" == "1" ]] && knulli-audio setSystemVolume unmute
        ;;
    esac
}

case "$1" in
    active)
        do_active
    ;;
esac

exit 0
