#!/bin/sh

TIMEOUT=30 # seconds
COUNT=0

is_discharging() {
    [ "$(knulli-battery-check status 2>/dev/null)" = "Discharging" ]
}

# Only run while discharging
if ! is_discharging; then
    exit 0
fi

# Start critical led blinking
if knulli-board-capability "pwrled"; then
    /usr/bin/knulli-power-led critical &
fi

# Countdown while discharging
while [ "$COUNT" -lt "$TIMEOUT" ]; do
    if ! is_discharging; then
        exit 0
    fi
    sleep 1
    COUNT=$((COUNT+1))
done

# If timer reached graceful shutdown
knulli-shutdown -s
exit 0
