#!/bin/sh

case "$1" in
  start)
    echo "Updating dynamic linker cache..."
    if [ -f /etc/multiarch ]; then
      /sbin/ldconfig -v
      echo "32-bit multiarch support enabled"
    fi
    ;;
  *)
    echo "Usage: $0 {start}"
    exit 1
esac

exit 0

