platform unix
PLATFORM unix
MAKEPORTABLE NO
CORE_JOB YES
MAKE make
CMAKE cmake
PATH /opt/fdata/knulli/rework-knulli-linux/knulli-linux/package/cores/libretro-super/overlay/toolchain-aarch64-v8a/bin:/opt/fdata/knulli/knulli-linux/output/h700/host/bin
CC aarch64-v8a-gcc
CXX aarch64-v8a-g++
CXX11 aarch64-v8a-g++
CXX17 aarch64-v8a-g++
AR aarch64-buildroot-linux-gnu-ar
RANLIB aarch64-buildroot-linux-gnu-ranlib
STRIP aarch64-buildroot-linux-gnu-strip
RARCH_DIST_DIR /opt/fdata/knulli/rework-knulli-linux/knulli-linux/package/cores/libretro-super/overlay/dist/aarch64-v8a
PATCH_SET aarch64-v8a
PATCH_TAGS aarch64 armv8 glesv2 buildroot
EXTRA_ARGS HAS_GLES=1 FORCE_GLES=1
CMAKE_EXTRA_ARGS -DCMAKE_TOOLCHAIN_FILE=/opt/fdata/knulli/rework-knulli-linux/knulli-linux/package/cores/libretro-super/overlay/cmake/aarch64-v8a-toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON
