platform unix
PLATFORM unix
MAKEPORTABLE NO
CORE_JOB YES
MAKE make
CMAKE cmake
PATH /opt/fdata/knulli/rework-knulli-linux/knulli-linux/package/cores/libretro-super/overlay/toolchain-atm7051/bin:/opt/fdata/knulli/knulli-linux/output/atm7039/host/bin
CC atm7051-gcc
CXX atm7051-g++
CXX11 atm7051-g++
CXX17 atm7051-g++
AR arm-buildroot-linux-gnueabihf-ar
RANLIB arm-buildroot-linux-gnueabihf-ranlib
STRIP arm-buildroot-linux-gnueabihf-strip
RARCH_DIST_DIR /opt/fdata/knulli/rework-knulli-linux/knulli-linux/package/cores/libretro-super/overlay/dist/armv7-neon-cortexa9-hf
PATCH_SET armv7-neon-cortexa9-hf
PATCH_TAGS armv7 neon cortex-a9 glesv2 buildroot
EXTRA_ARGS HAVE_NEON=1 HAS_GLES=1 FORCE_GLES=1
CMAKE_EXTRA_ARGS -DCMAKE_TOOLCHAIN_FILE=/opt/fdata/knulli/rework-knulli-linux/knulli-linux/package/cores/libretro-super/overlay/cmake/armv7-neon-cortexa9-hf-toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON
